path['cosmo'] = '/home/maanson/Speciale/connect/resources/class_public'
path['clik'] = '/home/maanson/Speciale/connect/resources/planck2018/code/plc_3.0/plc-3.01/'
path['montepython'] = '/home/maanson/Speciale/connect/resources/montepython_public'
