path['cosmo'] = '/home/maanson/Speciale/connectv2/resources/class_public'
path['clik'] = '/home/maanson/Speciale/connectv2/resources/planck2018/code/plc_3.0/plc-3.01/'
path['montepython'] = '/home/maanson/Speciale/connectv2/resources/montepython_public'
